name: Test Download Both Mod & Plugin

on:
    schedule:
        - cron: "0 0 * * *"
    workflow_dispatch:

permissions:
    contents: write

jobs:
    test-download-both:
        runs-on: ubuntu-latest

        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - uses: oven-sh/setup-bun@v2

            - name: Install dependencies
              run: bun install --frozen-lockfile

            - name: Test Download Both
              run: |
                  bun run src/index.ts both --download

                  MOD_FILE_PATH=$(find ./apks -name "*_universal*.apk" | head -n 1)
                  if [ -z "${MOD_FILE_PATH}" ]; then
                    echo "No MOD APK file found."
                    exit 1
                  fi

                  PLUGIN_FILE_PATH=$(find ./apks -name "*_plugin*.apk" | head -n 1)
                  if [ -z "${PLUGIN_FILE_PATH}" ]; then
                    echo "No Plugin APK file found."
                    exit 1
                  fi
